/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutUsIndexRouteImport } from './routes/about-us.index'
import { Route as AboutUsPageRouteImport } from './routes/about-us.$page'
import { Route as WhatWeDoSolutionRouteImport } from './routes/what-we-do.$solution'
import { Route as WhoWeHelpIndustryRouteImport } from './routes/who-we-help.$industry'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutUsIndexRoute = AboutUsIndexRouteImport.update({
  id: '/about-us/',
  path: '/about-us/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutUsPageRoute = AboutUsPageRouteImport.update({
  id: '/about-us/$page',
  path: '/about-us/$page',
  getParentRoute: () => rootRouteImport,
} as any)
const WhatWeDoSolutionRoute = WhatWeDoSolutionRouteImport.update({
  id: '/what-we-do/$solution',
  path: '/what-we-do/$solution',
  getParentRoute: () => rootRouteImport,
} as any)
const WhoWeHelpIndustryRoute = WhoWeHelpIndustryRouteImport.update({
  id: '/who-we-help/$industry',
  path: '/who-we-help/$industry',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about-us/$page': typeof AboutUsPageRoute
  '/what-we-do/$solution': typeof WhatWeDoSolutionRoute
  '/who-we-help/$industry': typeof WhoWeHelpIndustryRoute
  '/about-us/': typeof AboutUsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about-us/$page': typeof AboutUsPageRoute
  '/what-we-do/$solution': typeof WhatWeDoSolutionRoute
  '/who-we-help/$industry': typeof WhoWeHelpIndustryRoute
  '/about-us': typeof AboutUsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about-us/$page': typeof AboutUsPageRoute
  '/what-we-do/$solution': typeof WhatWeDoSolutionRoute
  '/who-we-help/$industry': typeof WhoWeHelpIndustryRoute
  '/about-us/': typeof AboutUsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about-us/$page'
    | '/what-we-do/$solution'
    | '/who-we-help/$industry'
    | '/about-us/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about-us/$page'
    | '/what-we-do/$solution'
    | '/who-we-help/$industry'
    | '/about-us'
  id:
    | '__root__'
    | '/'
    | '/about-us/$page'
    | '/what-we-do/$solution'
    | '/who-we-help/$industry'
    | '/about-us/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutUsPageRoute: typeof AboutUsPageRoute
  WhatWeDoSolutionRoute: typeof WhatWeDoSolutionRoute
  WhoWeHelpIndustryRoute: typeof WhoWeHelpIndustryRoute
  AboutUsIndexRoute: typeof AboutUsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about-us/': {
      id: '/about-us/'
      path: '/about-us'
      fullPath: '/about-us/'
      preLoaderRoute: typeof AboutUsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about-us/$page': {
      id: '/about-us/$page'
      path: '/about-us/$page'
      fullPath: '/about-us/$page'
      preLoaderRoute: typeof AboutUsPageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/what-we-do/$solution': {
      id: '/what-we-do/$solution'
      path: '/what-we-do/$solution'
      fullPath: '/what-we-do/$solution'
      preLoaderRoute: typeof WhatWeDoSolutionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/who-we-help/$industry': {
      id: '/who-we-help/$industry'
      path: '/who-we-help/$industry'
      fullPath: '/who-we-help/$industry'
      preLoaderRoute: typeof WhoWeHelpIndustryRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutUsPageRoute: AboutUsPageRoute,
  WhatWeDoSolutionRoute: WhatWeDoSolutionRoute,
  WhoWeHelpIndustryRoute: WhoWeHelpIndustryRoute,
  AboutUsIndexRoute: AboutUsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
